/*
 * Copyright (c) 2026, Luis Colorado <luiscoloradourcola@gmail.com>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package es.lcssl.chrono.gui;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.beans.PropertyChangeEvent;
import java.util.Objects;
import java.util.function.Supplier;
import java.util.ResourceBundle;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import static es.lcssl.chrono.gui.ChronographModel.format_timestamp;

/**
 * Class to manage a chronograph.
 *
 * The time is based on a {@code long}
 * milliseconds based method call.  It implements the {@link ChronographModel}
 * required to manage the {@link JChronograph} component class.
 *
 * @author Luis Colorado {@code <luiscoloradourcola@gmail.com>}
 */
public class DefaultChronographModel implements ChronographModel {

    /**
     * Internal {@link Logger} class.
     */
    private static final Logger   log =
            LogManager.getLogger(DefaultChronographModel.class);

    /**
     * {@code INTL} is the internationalized interface to the locale
     * based data.
     */
    static final ResourceBundle   INTL =
            ResourceBundle.getBundle(DefaultChronographModel.class.getName());

    /**
     * Format to output the three strings timestamp generated by the
     * {@link ChronographModel#format_timestamp(long, java.lang.String)}
     * routine.
     */
    private static final String   FORMAT = "{0}{1}{2}";

    /**
     * Format to output the log message output through the {@link #log}
     * device with the
     * {@link ChronographModel#format_timestamp(long, java.lang.String)
     * routine (internationalized version)
     */
    private static final String   FORMAT_LOG = INTL.getString("FORMAT_LOG");

    /**
     * {@code startTime} represents the timestamp at which the
     * {@code DefaultChronographModel} instance was started last time.
     * It's important as the total time measures is actually the difference
     * between the current timestamp and the {@link #startTime} timestamp.
     */
    private long                  startTime;

    /**
     * {@code lapseTime} represents the timestamp at which the
     * {@code DefaultChronographModel} instance was last lapsed.
     * The difference between the current timestamp and this value represents
     * the time of the last lapse of time.
     */
    private long                  lapseTime;

    /**
     * {@code stopTime} represent the last time the {@link #stop(long)} method
     * was called.  It is necessary to allow the time not to grow when the
     * {@link DefaultChronographModel} is stopped.
     */
    private long                  stopTime;

    /**
     * {@code running} represents a {@code boolean} value indicating if the
     * {@link DefaultChronographModel} is running or not.
     */
    private boolean               running;

    /**
     * The {@code timestamper} is a supplier of timestamp values.
     * This arrangement allows to select any source of timestamps that can
     * generate precise timing.  By default the
     * {@link System#currentTimeMillis() } static method is used.
     */
    private final Supplier<Long>  timestamper;

    /**
     * This instance of {@link PropertyChangeSupport} allows to register
     * {@link PropertyChangeListener}s to be called on the different kinds
     * of events that a {@link DefaultChronographModel} can handle.
     */
    private PropertyChangeSupport pcs;

    /**
     * The {@code name} property (bound) represents the name of the
     * {@link DefaultChronographModel} and allows the user to identify it
     * when several instances are running in parallel.
     */
    private String name;

    /**
     * Constructor providing a timestamp {@link Supplier}{@code <T>}.
     *
     * @param ts_provider the {@link Supplier}{@code <T>} that will provide
     * the timestamps for the parameter less versions of the triggering events
     * methods.
     */
    @SuppressWarnings("this-escape")
    public DefaultChronographModel(Supplier<Long> ts_provider) {
        this(ts_provider, null);
    }

    /**
     * Default constructor using {@link System#currentTimeMillis() } as the
     * providing function.
     */
    public DefaultChronographModel() {
        this(System::currentTimeMillis, null);
    }

    /**
     * Parameter full constructor.
     *
     * A {@link Supplier}{@code <}{@link Long}{@code >}
     * and a {@link String} name are given.
     *
     * @param ts_provider is the {@link Supplier}{@code <}{@link Long}{@code >}
     * that is needed when the {@link DefaultChronographModel} is not given
     * timestamps to process time.
     *
     * @param name is the name to be given to this
     * {@link DefaultChronographModel}
     */
    @SuppressWarnings("this-escape")
    public DefaultChronographModel(
            Supplier<Long> ts_provider,
            String name) {
        timestamper = ts_provider;
        pcs         = new PropertyChangeSupport(this);
        this.name   = name;
    }

    /**
     * Convenience constructor with only the {@code name} parameter.
     * the {@link #timestamper} defaults to {@link System#currentTimeMillis() }
     * static method.
     *
     * @param name is the name to be assigned to the constructor.
     */
    public DefaultChronographModel(String name) {
        this(System::currentTimeMillis, name);
    }

    /**
     * Auxiliary routine to simplify the five methods start(), stop(),
     * lapse(), restart(), reset().
     *
     * The function uses a {@link Runnable} to represent the
     * specific code to do between the {@code old_values} and
     * the {@code new_values} gathering.  In case {@code do_running}
     * is specified as {@code true} a {@link PropertyChangeEvent}
     * of the {@link CronographModel#RUNNING_PROPERTY} type will be
     * fired.
     *
     * @param ts is the timestamp of the event.
     * @param to_do is the {@link Runnable} to execute the specific
     *              method has to do.
     * @param type is the type of the event to fire.  One of the
     *             {@link String}s defined in {@link ChronographModel}.
     * @param do_running if {@code true}, another
     *             {@link PropertyChangeEvent} is fired on the
     *             {@link ChronographModel#RUNNING_PROPERTY} property.
     */
    private void do_method(
            long     ts,
            String   type,
            boolean  do_running,
            Runnable to_do)
    {
        long[] old_values = getIntervals(ts);
        to_do.run();
        long[] new_values = getIntervals(ts);
        if (do_running) {
            pcs.firePropertyChange(RUNNING_PROPERTY,
                    !running, running);
        }
        pcs.firePropertyChange(type, old_values, new_values);
        log.info(FORMAT_LOG,
                name, type, ts,
                format_timestamp(old_values[TOTAL_TIME], FORMAT),
                format_timestamp(old_values[LAPSE_TIME], FORMAT),
                format_timestamp(new_values[TOTAL_TIME], FORMAT),
                format_timestamp(new_values[LAPSE_TIME], FORMAT));
    }

    /**
     * Reset method.
     *
     * When the {@link DefaultChronographModel} is reset, the
     * {@link #startTime}, {@link #lapseTime} and {@link #stopTime} are all
     * set to the current timestamp passed as parameter.
     *
     * This has the lateral effect of resetting all measured values to 0s.
     *
     * It can be used independently of being {@link #running} or not.
     * @param ts the timestamp at which the {@link DefaultChronographModel}
     * was reset.
     */
    @Override
    public void reset(long ts) {
        do_method(ts, RESET_ACTION, false, () -> {
            startTime = lapseTime = stopTime = ts;
        });
    }

    /**
     * Start chronograph method.
     *
     * The {@link DefaultChronographModel} is started
     * to run.  If the chronograph is already running, this method has no
     * effect.
     *
     * To operate, first a {@code time_stopped} is computed by subtracting the
     * actual {@link #stopTime} from the actual timestamp.  Then both, the
     * {@link #startTime} and {@link #lapseTime} are added this amount.  After
     * that, the value of {@link #running} is set to {@code true} and the
     * corresponding events are fired.
     *
     * @param ts the current timestamp at which the start has occurred.
     */
    @Override
    public void start(long ts) {
        if (running) return;

        do_method(ts, START_ACTION, true, () -> {
            long time_stopped = ts - stopTime;
            startTime += time_stopped;
            lapseTime += time_stopped;
            running    = true;
        });
    }

    /**
     * This effectively stops the chronograph, firing the necessary events to
     * event listeners.
     *
     * If the chronograph is already stopped, nothing happens.  Else, the value
     * of the current timestamp is saved in {@link #stopTime} and
     * {@link #running} is set to {@code false}.
     *
     * @param ts the time at which the {@link DefaultChronographModel} was
     * stopped.
     */
    @Override
    public void stop(long ts) {
        if (!running) return;

        do_method(ts, STOP_ACTION, true, () -> {
            running  = false;
            stopTime = ts;
        });
    }

    /**
     * This method has the same effect of resetting the chronograph while it
     * is running.  In case the chronograph is stopped, nothing happens.
     *
     * The chronograph stores the current timestamp in {@link #startTime} and
     * {@link #lapseTime}.
     *
     * @param ts The time at which the chronograph has been stopped.
     */
    @Override
    public void restart(long ts) {
        if (!running) return;

        do_method(ts, RESTART_ACTION, true, () -> {
            startTime = lapseTime = ts;
        });
    }

    /**
     * This method inserts a lapse restart.  The value of the current timestamp
     * is stored in {@link #lapseTime}, effectively resetting its time.
     *
     * @param ts the current timestamp at which the chronograph was lapsed.
     */
    @Override
    public void lapse(long ts) {
        do_method(ts, LAPSE_ACTION, false, () -> {
            lapseTime = ts;
        });
    }

    /**
     * This method gives the current times for the Total time (at index
     * {@link #TOTAL_TIME} and the lapse time (at index
     * {@link #LAPSE_TIME}.
     *
     * @param ts the current timestamp at which the values are required.
     *
     * @return a {@code long[]} array with two values for the total time
     * (at index {@link #TOTAL_TIME}) and lapse time (at index
     * {@link #LAPSE_TIME}.
     */
    @Override
    public long[] getIntervals(long ts) {
        long stop_correction = isRunning()
                             ? 0
                             : ts - stopTime;
        return new long[] {
            ts - startTime - stop_correction,
            ts - lapseTime - stop_correction };
    }

    /**
     * Getter for the {@link #name} property (bound).
     *
     * @return the {@link String} value of the name.
     */
    @Override
    public String getName() {
        return name;
    }

    /**
     * Setter for the {@link #name} property (bounded).
     *
     * A {@link PropertyChangeEvent} is fired to each listener registered
     * using the
     * {@link #addPropertyChangeListener(java.lang.String,
     * java.beans.PropertyChangeListener) }
     * and
     * {@link #removePropertyChangeListener(java.lang.String,
     * java.beans.PropertyChangeListener) }.
     * @param new_name is the new name to be assigned to this
     * {@link DefaultChronographModel}.
     */
    @Override
    public void setName(String new_name) {
        String old_name = getName();
        this.name = new_name;
        if (!Objects.equals(old_name, new_name))
            pcs.firePropertyChange(NAME_PROPERTY,
                    old_name, new_name);
    }

    /**
     * Parameter less version of the {@link #reset(long) } method.
     *
     * @see #reset(long)
     */
    public void reset() {
        reset(timestamper.get());
    }

    /**
     * Parameter less version of the {@link #start(long) } method.
     *
     * @see #start(long)
     */
    public void start() {
        start(timestamper.get());
    }

    /**
     * Parameter less version of the {@link #restart(long) } method.
     *
     * @see #restart(long)
     */
    public void restart() {
        restart(timestamper.get());
    }

    /**
     * Parameter less version of the {@link #lapse(long) } method.
     *
     * @see #lapse(long)
     */
    public void lapse() {
        lapse(timestamper.get());
    }

    /**
     * Parameter less version of the {@link #stop(long) } method.
     *
     * @see #stop(long)
     */
    public void stop() {
        stop(timestamper.get());
    }

    /**
     * Getter for the {@link #running} property (bound).
     *
     * @return the {@code boolean} value of the property.
     */
    @Override
    public boolean isRunning() {
        return running;
    }

    /**
     * Asks the timestamp provider for the current time.
     *
     * @return a timestamp of the current time returned by the
     * {@link #timestamper} {@link Supplier}{@code <}{@link Long}{@code >}.
     */
    @Override
    public long getTimestamp() {
        return timestamper.get();
    }

    /**
     * Provides the timestamp of the {@link #startTime} for the case you
     * need to get when this {@link DefaultChronographModel} was last started.
     *
     * @return the timestamp of the last {@link #startTime}.
     */
    public long getStartTime() {
        return startTime;
    }

    /**
     * Registry function for {@link PropertyChangeEvent}s.
     *
     * Registers a {@link PropertyChangeListener} to be notified when a property
     * changes as a result of setting a property explicitly (e.g. {@link #name}
     * or any of the methods {@link #reset() }, {@link #reset(long) },
     * {@link #start() }, {@link #start(long) }, {@link #restart() },
     * {@link #restart(long) }, {@link #lapse() }, {@link #lapse(long) },
     * {@link #stop() } or {@link #stop(long) }, and the bound properties
     * {@link #running} and {@link #name}.
     *
     * @param property_name is the property name ({@link String}).  The used
     * property names used actually are:
     * <ul>
     *   <li>{@link #RUNNING_PROPERTY} for a change in the running state of the
     *       {@link DefaultChronographModel}.
     *   <li>{@link #NAME_PROPERTY} for a change in name.
     *   <li>{@link #START_ACTION} for a {@link #start(long) } or
     *       {@link #start() } event.
     *   <li>{@link #STOP_ACTION} for a {@link #stop(long) } or {@link #stop() }
     *       event.
     *   <li>{@link #LAPSE_ACTION} for a {@link #lapse(long) } or a
     *       {@link #lapse() } event.
     *   <li>{@link #RESTART_ACTION} for a {@link #restart(long) } or a
     *       {@link #restart() } event.
     *   <li>{@link #RESET_ACTION} for a {@link #reset() } or a
     *       {@link #reset(long) } event.
     * </ul>
     *
     * @param listener is the {@link PropertyChangeListener} to be installed.
     */
    @Override
    public void addPropertyChangeListener(
            String                 property_name,
            PropertyChangeListener listener) {
        pcs.addPropertyChangeListener(property_name, listener);
    }

    /**
     * Removes a {@link PropertyChangeListener} from the appropiate list.
     *
     * For the list of property names, see
     * {@link #addPropertyChangeListener(java.lang.String,
     * java.beans.PropertyChangeListener) }.
     *
     * @param property_name is the property name.
     *
     * @param listener is the {@link PropertyChangeListener} to be
     * unregistered.
     *
     * @see #addPropertyChangeListener(java.lang.String,
     * java.beans.PropertyChangeListener)
     */
    @Override
    public void removePropertyChangeListener(
            String                 property_name,
            PropertyChangeListener listener) {
        pcs.removePropertyChangeListener(property_name, listener);
    }
}
