# Copyright (c) 2026, Luis Colorado {@code <luiscoloradourcola@gmail.com>}.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

#A font name
LABELS_FONT=Courier 16
#Value assigned to the Total JLabel of the Chronograph
TOTAL_TITLE=Total
LAPSE_TITLE=Lapse
#First parameter is the button action name, second is the duration of the click in msec.
BUTTON_CLICK_DELAY_MESSAGE_FORMAT={}: Click duration: {}
#Value of the start action name for the start button
START_ACTION_NAME=Start
#Value of the action name for lapse button
LAPSE_ACTION_NAME=Lapse
#Name of the action for the Stop button
STOP_ACTION_NAME=Stop
#Name of the action associated with the Reset button
RESET_ACTION_NAME=Reset
#format for presenting in JLabel the cronograph values {0} is used for the locale formated number of days
#(1} is the HH:MM:SS timestamp, and {2} is the .mmm milliseconds value.
TIMESTAMP_LABEL_FORMAT=<html><font size=+2>{0}{1}</font>{2}

# icon paths (as a resource name local path)
START_ICON=images/start.png
STOP_ICON=images/stop.png
LAPSE_ICON=images/lapse.png
RESET_ICON=images/reset.png
